Modal Bottom Sheet Dialog
mfathur/babel-guru pull request #20
Opened 2021-09-28 11:52 UTC by S0ULB0Y

Implement modal bottom sheet dialog

2021-09-28 16:19 UTC, mfathur requested changes

2021-09-28 16:19 UTC, mfathur commented on app/src/main/res/layout/fragment_modal_bottom_sheet.xml
> +        android:id="@+id/btn_batal"
lebih baik kalo bhs inggris :)

2021-09-28 16:19 UTC, mfathur commented on app/src/main/res/layout/fragment_modal_bottom_sheet.xml
> +        android:id="@+id/btn_selesai"
lebih baik kalo bhs inggris:)

2021-09-28 16:19 UTC, mfathur commented on app/src/main/res/values/strings.xml
> +    <string name='model_bottom_sheet_Tulisdisini'>Tulis di sini..</string>
nama id string nya dibikin bhs inggris aja

2021-09-28 16:31 UTC, S0ULB0Y commented on app/src/main/res/drawable/rounded_dialog_bottomsheet.xml
> +        android:topRightRadius="30dp"/>
enaknya berapa btw?

2021-09-28 17:04 UTC, mfathur commented on app/src/main/res/values/themes.xml
> -        <item name="android:textSize">@dimen/font_size_96sp</item>
ini typography buat headlinenya kehapus kah?

2021-09-29 10:38 UTC, mfathur approved these changes

2021-09-29 10:39 UTC, merged